cart/urls.py
from django.urls import path
from cart import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<int:id>', views.add, name='add_item'),
    path('remove/<int:id>', views.remove, name="remove_item"),
    path('cart', views.remove_all, name="remove_all"),
    path('purchase/', views.purchase, name='purchase'),
    path('purchase/success/', views.purchase_success, name='purchase_success'),
    path('purchase/failed/', views.purchase_failed, name='purchase_failed'),
]

game_shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from game_shop_app import views


urlpatterns = [
    path('', include('game_shop_app.urls')),
    path('admin/', admin.site.urls),
    path('registration/', views.RegisterView.as_view(), name='register'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(
        template_name="registration/password-change.html"), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password-change-done.html'), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        template_name="registration/password-reset-form.html"), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="registration/password-reset-done.html"), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password-reset-confirm.html"), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="registration/password-reset-complete.html"), name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_shop_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Genre(models.Model):
    genre_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.genre_name

    objects = models.Manager


class Platform(models.Model):
    platform_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.platform_name

    objects = models.Manager


class Developer(models.Model):
    developer_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.developer_name

    objects = models.Manager


class Publisher(models.Model):
    publisher_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.publisher_name

    objects = models.Manager


class Language(models.Model):
    language_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.language_name

    objects = models.Manager


class GameScreenshots(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(blank=True, null=True, upload_to="screenshots/")
    description = models.TextField()
    game = models.ForeignKey("Game", blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    objects = models.Manager


class Game(models.Model):
    game_name = models.CharField(max_length=100)
    description = models.TextField()
    genres = models.ManyToManyField(Genre)
    release_date = models.DateField()
    developer = models.ForeignKey("Developer", blank=True, null=True, on_delete=models.PROTECT)
    publisher = models.ForeignKey("Publisher", blank=True, null=True, on_delete=models.PROTECT)
    platforms = models.ManyToManyField(Platform)
    languages = models.ManyToManyField(Language)
    price = models.FloatField(blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)
    minimum_requirements = models.TextField()
    recommended_requirements = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to="games/")
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.game_name

    objects = models.Manager


class Order(models.Model):
    MY_CHOICES = (
        ('Обработан', 'Обработан'),
        ('Не обработан', 'Не обработан'),
    )
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.PROTECT)
    order_items = models.JSONField(blank=True, null=True)
    card = models.CharField(max_length=20, blank=True, null=True)
    cvv_code = models.PositiveIntegerField(blank=True, null=True)
    card_validity_period = models.CharField(max_length=5, blank=True, null=True)
    total_price = models.FloatField(blank=True, null=True)
    order_date = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=15, choices=MY_CHOICES, blank=True, null=True)

    def __str__(self):
        return f"{self.user}'s order {self.order_date}"

    objects = models.Manager



templates/about.html
{% extends 'layout/base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center">
    <div class="d-flex flex-column align-items-center justify-content-center px-5">
        <div class="card border-secondary my-lg-5 p-3">
            <h3 class="list-inline-item">Game Fellow</h3>
            <p class="card-text">
                Game Fellow - Интернет-магазин предназначенный для размещения игр различных
                издателей и разработчиков. У нас вы можете найти игры на любой вкус и цвет! Нравятся шутеры?
                У нас они есть! Различные головоломки или стратегии для настоящих мыслителей? Имеются! У нас вы найдете все самые популярные игры последних лет,
                а также новинки и эксклюзивы, которые только что появились на рынке.
                Мы постоянно обновляем наш каталог, чтобы вы могли быть уверены, что найдете здесь всё, что искали.<br><br>
                Заинтересованы в сотрудничестве? <br>
                <h4>Контактная информация: </h4>
                Почта: gamefellow@mail.ru<br>
                Телефон: +79093678913
            </p>
        </div>
    </div>
</div>
{% endblock %}

templates/card-item.html
<div class="card border-secondary" style="display: inline-block;">

    <div class="game-image-container">
        <img class="game-image" src="{{game.image.url}}" alt="Preview">
    </div>

    <div class="card-img-overlay lh">
        <h3 class="card-title">{{game.game_name}}</h3>
        <span class="card-text"><b>Жанры:</b></span>
        {% for g in game.genres.all %}
        <span class="card-text">{{g.genre_name}}, </span>
        {% endfor %}
        <span class="card-text" style="display:inline-block;"><b>Год выпуска</b>: {{game.release_date}}</span>
        <span class="card-text" style="display:inline-block;"><b>Разработчик:</b> {{game.developer}}</span>
        <span class="card-text" style="display:inline-block;"><b>Издатель:</b> {{game.publisher}}</span>
        <span class="card-text" style="display:inline-block;"><b>Платформы:</b> </span>
        {% for p in game.platforms.all %}
            <span class="card-text"> {{p.platform_name}}, </span>
        {% endfor %}

        <br><span class="card-text" style="display:inline-block; margin-bottom: 20px;"><b>Цена:</b> {{game.price}} Рублей</span>

        <button class="btn btn-outline-dark" onclick="window.location.href = '{% url 'game_details' game.slug %}'">
            Подробнее...
        </button>
    </div>

</div>

templates/empty-games-list.html
{% extends 'layout/base.html' %}

{% block title %}Not Found{% endblock %}

{% block content %}
    <div class="d-flex align-items-center justify-content-center">
        <div class="card border-secondary my-lg-3 p-3" style="border-width: 2px;">
            {% include 'layout/search-field.html' %}
            <h3 class="title-center text-center">Ничего не найдено</h3>
          <p class="text-center">{{ text }}</p>
            {% include 'layout/catalog-btn.html' %}
        </div>
    </div>
{% endblock %}

templates/game-details.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="card border-secondary my-2 my-sm-3 my-lg-3 p-3" style="border-width: 2px;">
    <div class="d-flex">
        <img class="game-image mx-auto my-2 my-sm-3 my-lg-5 p-3" src="{{game.image.url}}" alt="Preview">

        <div class="container px-4">
            <h3 class="card-title">{{game.game_name}}</h3>
            <p class="card-text"><b>Описание</b>: {{ game.description }}</p>

            <div class="card border-dark p-4 text-center" style="display: inline-block;">
                {% for screenshot in game.gamescreenshots_set.all%}
                <img class="game-screenshot " src="{{ screenshot.image.url }}" alt="{{ screenshot.description }}">
                {% endfor %}
            </div>

            <div style="margin: 7px 0px;">
                <br><span class="card-text"><b>Жанры:</b></span>
                {% for g in game.genres.all %}
                <span class="card-text">{{g.genre_name}}, </span>
                {% endfor %}
            </div>
            <p class="card-text"><b>Дата выпуска</b>: {{game.release_date}}</p>
            <p class="card-text"><b>Разработчик</b>: {{game.developer}}</p>
            <p class="card-text"><b>Издатель</b>: {{game.publisher}}</p>
            <span class="card-text"><b>Платформы:</b></span>
            {% for p in game.platforms.all %}
            <span class="card-text">{{p.platform_name}},</span>
            {% endfor %}

            <br><br><span class="card-text" style="display:inline-block;"><b>Языки:</b> </span>
            {% for l in game.languages.all %}
            <span class="card-text"> {{l.language_name}}, </span>
            {% endfor %}

            <br><br>
            <p class="card-text"><b>Цена</b>: {{game.price}} Рублей</p>
            <p class="card-text"><b>Минимальные системные требования</b>:<br>{{game.minimum_requirements}}</p>
            <p class="card-text"><b>Рекомендуемые системные требования</b>:<br>{{game.recommended_requirements}}</p>
            {% if user.is_authenticated %}
            <div class="d-inline-flex">
                {% include 'favourites/add-favourite.html' with type='game' id=game.id %}
            </div>
            <div class="d-inline-flex">
                {% include 'cart/add-item.html' with type='game' id=game.id %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/home_page.html
{% extends 'layout/base.html' %}

{% block content %}

{% include 'layout/filter-bar.html'%}

<div class="mx-auto text-center my-2 my-sm-3 my-lg-2 p-5">
    {% include 'layout/search-field.html' %}
        {% for game in games %}
            {% include 'card-item.html'%}
<!--            {% if user.is_authenticated %}-->
<!--            <div class="d-inline-flex">-->
<!--                {% include 'favourites/add-favourite.html' with type='game' id=game.id %}-->
<!--                {% include 'cart/add-item.html' with type='game' id=game.id%}-->
<!--            </div>-->
<!--            {% endif %}-->
        {% endfor %}
</div>

{% endblock %}

templates/profile-edit.html
{% extends 'layout/base.html' %}

{% block title %}Profile Edit{% endblock %}

{% block content %}
    <div class="d-flex align-items-center justify-content-center">
        <div class="card border-secondary my-lg-3 p-3" style="border-width: 2px;">
            <form method="post" class="col-md-8 offset-md-2">
                <h3>Редактирование профиля:</h3>
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-dark" value="Сохранить">
            </form>
        </div>
    </div>
{% endblock %}

templates/profile.html
{% extends 'layout/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center">
    <div class="card border-secondary my-lg-3 p-4" style="border-width: 2px;">
        <h1>Профиль:</h1>
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.last_name }} </p>
        <p>Имя пользователя: {{ user.username }}</p>
        <p>Почта: {{ user.email }} </p>

        <div class="button-group">
            <button class="btn btn-danger" onclick="window.location.href = '{% url 'logout' %}?next={% url 'home' %}'">
                Выйти
            </button>

            <button class="btn btn-secondary" style="color: white"
                    onclick="window.location.href = '{% url 'password_change' %}'">
                Поменять пароль
            </button>

            <button class="btn btn-dark" onclick="window.location.href = '{% url 'profile_edit' %}'">
                Редактировать профиль
            </button>
        </div>

    </div>
</div>

<div class="d-flex align-items-center justify-content-center">
    <div class="card profile-games border-secondary my-lg-3 p-4">
        <h2>Заказы:</h2>

        <div class="d-flex p-2">
            {% for order_id, order in orders.items %}
            <a href="{% url 'game_details' order.game.slug %}">
                <img class="game-mini-image" src="{{ order.game.image.url }}" alt="Обложка игры">
            </a>
            <div class="container">
                <p>(Место для ключей)</p>
                <p>Количество: {{ order.quantity }}</p>
                <p>Дата заказа: {{ order.order_date }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}